### ISSUE TITLE
[JOSE] add a section in the documentation about FAIRness of the datasets

### ISSUE THREAD

**Issue by BenjMy** [cgre-aachen/gemgis_data#15]
xref https://github.com/openjournals/jose-reviews/issues/185

Hosting the datasets and notebooks in a separate repo is perfectly relevant particularly to provide clear guidelines on the data FAIRness.

I suggest adding details in the README and in the documentation covering how FAIR are the dataset provided (but also for future contributions), in particular:
- Under what Licence are the data distributed? I've seen that the authors cited individually the map source for each notebook but it should also clearly be stated on the README and in the doc.
- Is there a plan for long-term archiving of the data? into Zenodo for instance?
- Is there a plan for version-controlled data? data could be fetched (using Pooch for example).

**Comment by AlexanderJuestel** [comment]
Dear @BenjMy, 

thanks for opening this issue. This is certainly an important topic. 

Let me get straight to your 2rd point. Once the JOSE submission is ready to be accepted, there should be a first archived version which we usually store on Zenodo, So we could update that once major changes or new notebooks have been added. 

Regarding your 3rd point: The data is currently hosted within the repository but also on a university OwnCloud storage. The data will then be fetched using pooch actually. 

I will work on your first point one of these days then!

Cheers 
Alex

**Comment by AlexanderJuestel** [comment]
A section about the FAIR principles was added to the Documentation in https://github.com/cgre-aachen/gemgis/commit/be5d3a2f45475a46a2b96f8d08f7dccaad46dfa5

Zenodo archiving is set up already. Pooch is also used to fetch the data. The license issue is discussed these days.

**Comment by AlexanderJuestel** [comment]
Closing this issue as a FAIR section was added
