### ISSUE TITLE
[JOSE] First Release and Archive of the datasets

### ISSUE THREAD

**Issue by BenjMy** [cgre-aachen/gemgis_data#17]
xref https://github.com/openjournals/jose-reviews/issues/185

Yet there is no release of the proposed package and archive of the datasets. 
I suggest creating one (even if it is a beta) and linking it to a data repository to assign a DOI (GitHub integration with Zenodo is probably the easiest way see [here](https://docs.github.com/fr/repositories/archiving-a-github-repository/referencing-and-citing-content)

**Comment by AlexanderJuestel** [comment]
Hello @BenjMy, 

this relates back to #13 where I was wondering if you would like to see a Pypi and conda release. The Zenode integration is certainly something we can implement. 

Cheers
Alex

**Comment by AlexanderJuestel** [comment]
The integration with Zenodo was enabled and I have made a first pre-release. The next pre-release or final release then will contain all your requested changes. I also added a cff file for a better citation: https://github.com/cgre-aachen/gemgis_data/blob/main/CITATION.cff

https://zenodo.org/account/settings/github/repository/cgre-aachen/gemgis_data#

![image](https://user-images.githubusercontent.com/45469915/210047609-791f49e3-ba95-43ed-a9d6-0621961dd193.png)

**Comment by AlexanderJuestel** [comment]
@BenjMy, 

I tried uploading the package to PyPi, however, the repo is too large (see screenshot). 

What we could do now is moving all the data to our owncloud and just download the tutorial data using pooch? What would you think about that?

![image](https://user-images.githubusercontent.com/45469915/210092346-3c553cfb-fca5-438e-9253-6f5999779923.png)

**Comment by BenjMy** [comment]
Sounds good to consider pooch to fetch the data. 
I don't know how much work is required for that. Actually, I've seen that you already have it implemented on gemgis no? 
[gemgis/download_gemgis_data.py](https://github.com/cgre-aachen/gemgis/blob/e99b00138a0226eaeba760568d14eacbc8ed0165/gemgis/download_gemgis_data.py)

**Comment by AlexanderJuestel** [comment]
Hey, 

yes, it is already implemented in GemGIS and I have the data already uploaded to our server, so not that much more work is required here, actually. 

But since you said, that we do not need a PyPi release of `gemgis_data`, this becomes obsolete and we can keep the data in the repo where all users can see it right away?

**Comment by BenjMy** [comment]
Ok agreed. Please feel free to close the issue.
